import { IDataRecord } from './records.interface';

export const MOCK_RECORDS: IDataRecord[] = [
  {
    id: 'esMuuS',
    name: 'Nombre 1',
    description: 'Descripción 1',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-20',
    date_revision: '2025-01-20',
  },
  {
    id: 'cEDIux',
    name: 'Nombre 2',
    description: 'Descripción 2',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-14',
    date_revision: '2025-02-14',
  },
  {
    id: 'wGXBww',
    name: 'Nombre 3',
    description: 'Descripción 3',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-29',
    date_revision: '2025-03-29',
  },
  {
    id: 'HeFzZb',
    name: 'Nombre 4',
    description: 'Descripción 4',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-29',
    date_revision: '2025-01-29',
  },
  {
    id: 'PLpMwY',
    name: 'Nombre 5',
    description: 'Descripción 5',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-13',
    date_revision: '2025-01-13',
  },
  {
    id: 'hVGVTz',
    name: 'Nombre 6',
    description: 'Descripción 6',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-13',
    date_revision: '2025-02-13',
  },
  {
    id: 'GZFyuo',
    name: 'Nombre 7',
    description: 'Descripción 7',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-14',
    date_revision: '2025-04-14',
  },
  {
    id: 'gfdFiJ',
    name: 'Nombre 8',
    description: 'Descripción 8',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-20',
    date_revision: '2025-03-20',
  },
  {
    id: 'IfCjtP',
    name: 'Nombre 9',
    description: 'Descripción 9',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-11',
    date_revision: '2025-04-11',
  },
  {
    id: 'jFGFUf',
    name: 'Nombre 10',
    description: 'Descripción 10',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-05',
    date_revision: '2025-03-05',
  },
  {
    id: 'iQsUIv',
    name: 'Nombre 11',
    description: 'Descripción 11',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-26',
    date_revision: '2025-01-26',
  },
  {
    id: 'tPHXYG',
    name: 'Nombre 12',
    description: 'Descripción 12',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-29',
    date_revision: '2025-02-29',
  },
  {
    id: 'oUdaTG',
    name: 'Nombre 13',
    description: 'Descripción 13',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-28',
    date_revision: '2025-01-28',
  },
  {
    id: 'WQEABj',
    name: 'Nombre 14',
    description: 'Descripción 14',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-28',
    date_revision: '2025-02-28',
  },
  {
    id: 'sfiaCv',
    name: 'Nombre 15',
    description: 'Descripción 15',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-17',
    date_revision: '2025-03-17',
  },
  {
    id: 'gCnJpw',
    name: 'Nombre 16',
    description: 'Descripción 16',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-20',
    date_revision: '2025-03-20',
  },
  {
    id: 'dcwvkC',
    name: 'Nombre 17',
    description: 'Descripción 17',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-11',
    date_revision: '2025-02-11',
  },
  {
    id: 'YBlTqt',
    name: 'Nombre 18',
    description: 'Descripción 18',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-08',
    date_revision: '2025-01-08',
  },
  {
    id: 'ZxCXvg',
    name: 'Nombre 19',
    description: 'Descripción 19',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-07',
    date_revision: '2025-04-07',
  },
  {
    id: 'UYPvoK',
    name: 'Nombre 20',
    description: 'Descripción 20',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-17',
    date_revision: '2025-03-17',
  },
  {
    id: 'pFPrns',
    name: 'Nombre 21',
    description: 'Descripción 21',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-09',
    date_revision: '2025-04-09',
  },
  {
    id: 'hvNUZE',
    name: 'Nombre 22',
    description: 'Descripción 22',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-06',
    date_revision: '2025-01-06',
  },
  {
    id: 'gTxASf',
    name: 'Nombre 23',
    description: 'Descripción 23',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-09',
    date_revision: '2025-04-09',
  },
  {
    id: 'WLUnAT',
    name: 'Nombre 24',
    description: 'Descripción 24',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-08',
    date_revision: '2025-01-08',
  },
  {
    id: 'nsIMcs',
    name: 'Nombre 25',
    description: 'Descripción 25',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-04',
    date_revision: '2025-02-04',
  },
  {
    id: 'bHjAsI',
    name: 'Nombre 26',
    description: 'Descripción 26',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-15',
    date_revision: '2025-02-15',
  },
  {
    id: 'tbYBQL',
    name: 'Nombre 27',
    description: 'Descripción 27',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-29',
    date_revision: '2025-03-29',
  },
  {
    id: 'cDEmAt',
    name: 'Nombre 28',
    description: 'Descripción 28',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-10',
    date_revision: '2025-01-10',
  },
  {
    id: 'gxppji',
    name: 'Nombre 29',
    description: 'Descripción 29',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-16',
    date_revision: '2025-01-16',
  },
  {
    id: 'bgQODt',
    name: 'Nombre 30',
    description: 'Descripción 30',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-01',
    date_revision: '2025-04-01',
  },
  {
    id: 'AVpLwK',
    name: 'Nombre 31',
    description: 'Descripción 31',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-11',
    date_revision: '2025-02-11',
  },
  {
    id: 'nFNbRl',
    name: 'Nombre 32',
    description: 'Descripción 32',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-19',
    date_revision: '2025-01-19',
  },
  {
    id: 'PaMlfX',
    name: 'Nombre 33',
    description: 'Descripción 33',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-16',
    date_revision: '2025-01-16',
  },
  {
    id: 'vMaAHQ',
    name: 'Nombre 34',
    description: 'Descripción 34',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-12',
    date_revision: '2025-02-12',
  },
  {
    id: 'qmFmEL',
    name: 'Nombre 35',
    description: 'Descripción 35',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-04',
    date_revision: '2025-03-04',
  },
  {
    id: 'FAkpSP',
    name: 'Nombre 36',
    description: 'Descripción 36',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-08',
    date_revision: '2025-02-08',
  },
  {
    id: 'YyFAvj',
    name: 'Nombre 37',
    description: 'Descripción 37',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-26',
    date_revision: '2025-04-26',
  },
  {
    id: 'JbyHSQ',
    name: 'Nombre 38',
    description: 'Descripción 38',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-16',
    date_revision: '2025-02-16',
  },
  {
    id: 'ieiJIt',
    name: 'Nombre 39',
    description: 'Descripción 39',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-19',
    date_revision: '2025-03-19',
  },
  {
    id: 'arRQRp',
    name: 'Nombre 40',
    description: 'Descripción 40',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-14',
    date_revision: '2025-04-14',
  },
  {
    id: 'YwGXHZ',
    name: 'Nombre 41',
    description: 'Descripción 41',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-24',
    date_revision: '2025-04-24',
  },
  {
    id: 'lHpIXH',
    name: 'Nombre 42',
    description: 'Descripción 42',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-31',
    date_revision: '2025-01-31',
  },
  {
    id: 'ppdqWQ',
    name: 'Nombre 43',
    description: 'Descripción 43',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-01-10',
    date_revision: '2025-01-10',
  },
  {
    id: 'jksEXD',
    name: 'Nombre 44',
    description: 'Descripción 44',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-02',
    date_revision: '2025-02-02',
  },
  {
    id: 'UwgyUh',
    name: 'Nombre 45',
    description: 'Descripción 45',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-01',
    date_revision: '2025-03-01',
  },
  {
    id: 'zGWRVY',
    name: 'Nombre 46',
    description: 'Descripción 46',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-02-17',
    date_revision: '2025-02-17',
  },
  {
    id: 'CSkIUz',
    name: 'Nombre 47',
    description: 'Descripción 47',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-08',
    date_revision: '2025-03-08',
  },
  {
    id: 'umuRmu',
    name: 'Nombre 48',
    description: 'Descripción 48',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-28',
    date_revision: '2025-04-28',
  },
  {
    id: 'mXtPxK',
    name: 'Nombre 49',
    description: 'Descripción 49',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-03-24',
    date_revision: '2025-03-24',
  },
  {
    id: 'kgsJdC',
    name: 'Nombre 50',
    description: 'Descripción 50',
    logo: 'https://raw.githubusercontent.com/scorpion2211/test/master/src/assets/images/box.png',
    date_release: '2024-04-19',
    date_revision: '2025-04-19',
  },
];
